### ISSUE TITLE
Deploying application to WildFly images via Volumes mounts doesn't work anymore

### ISSUE THREAD

**Issue by rafabene** [redhat-developer/docker-java#4]
Docker mounts volumes as root. There's a request to mount [Add ability to mount volume as user other than root ](https://github.com/docker/docker/issues/2259)

Since 14 October 2014 WildFly  is run as the jboss user which has the uid/gid set to 1000  as you can see here: https://hub.docker.com/r/jboss/wildfly/

This restricts the user to read any mounted volumes. We should fully refactor the section https://github.com/redhat-developer/docker-java/blob/javaone2015/chapters/docker-deployment-options.adoc#start-application-server

**Comment by rafabene** [comment]
I still not able to make it work.

This is the exception:

```
23:38:51,030 ERROR [org.jboss.as.controller.management-operation] (ServerService Thread Pool -- 13) WFLYCTL0013: Operation ("add") failed - address: ([
    ("subsystem" => "deployment-scanner"),
    ("scanner" => "default")
]): java.lang.IllegalArgumentException: WFLYDS0024: /opt/jboss/wildfly/standalone/deployments is not writable
    at org.jboss.as.server.deployment.scanner.FileSystemDeploymentService.<init>(FileSystemDeploymentService.java:190)
```

This is the permissions that I see when I run 

```
docker run --name wildfly --rm -p 8080:8080 -v `pwd`/deployments:/opt/jboss/wildfly/standalone/deployments/:rw classroom.example.com:5000/wildfly bash -c "ls -l /opt/jboss/wildfly/standalone"

otal 12
drwxr-xr-x 2 jboss jboss 4096 Aug 28 08:46 configuration
drwxr-xr-x 2 root  root    40 Oct 15 23:20 deployments
drwxr-xr-x 3 jboss jboss 4096 Jul 24 02:01 lib
drwxr-xr-x 3 jboss jboss 4096 Jul 24 02:01 tmp
```

I'm afraid that it we will need to create a new Custom WF image. Please, let me know what you think .

**Comment by myfear** [comment]
Ok, I researched a bit. As a matter of fact, this error doesn't come up on windows, because they only mount the /c/User/<USER> folder anyway. And this obviously doesn't give any errors at all.

We will have to build our own image in this case to make it work on Linux/Mac OS. 

Or we enhance the lab the way, that we let users run into this and explain the security concepts (with links) and point to potential solutions. That would be my favorite right now.

**Comment by rafabene** [comment]
After some research, I saw that It doesn't happen on OSX as well, just on Fedora Linux actually

**Comment by rafabene** [comment]
It seems that a custom image doesn't help. It's more related to the way the docker-machine mount the host folder. On Linux you aren't suppose to need docker-machine so I was able to make it work using raw docker services running on Fedora.

**Comment by myfear** [comment]
I expect most of the attendees to use Windows and mac. Should we document
the Linux specific 'problem' and just keep the rest?

**Comment by rafabene** [comment]
Yeap. I think it worth to mention the Linux issue and say that it doesn't happen on raw Linux machines. Please, give me more 24 hours to try another workaround.

**Comment by rafabene** [comment]
All the workaround that I found was too complicated to explain and could cause more doubts than benefits. It's better that we mention that Linux boxes should run native docker daemon to have access to host folder (It works for Mac and Windows). More info: https://github.com/docker/machine/issues/1826

**Comment by bwnyasse** [comment]
I'm running on ubuntu , and I'm facing exactly the same error 

Distributor ID: Ubuntu
Release:    15.04
Codename:   vivid

**Comment by rafabene** [comment]
Hi @bwnyasse A workaround for it is to run the Docker Daemon on your Ubuntu host instead of inside the VirtualBox/Docker-Machine/Boot2Docker. Thanks for the feedback.

**Comment by bwnyasse** [comment]
@rafabene the workaround actually fixes the problem. Thanks.

**Comment by rafabene** [comment]
You're welcome :)

**Comment by rafabene** [comment]
Now the instruction is clear that docker-machine is only needed for Mac and Windows: https://github.com/redhat-developer/docker-java/blob/devoxxma2015/chapters/docker-setup.adoc#create-lab-docker-host-for-windows-and-mac - This fixes this issue
