### ISSUE TITLE
Change Virtualbox 5.0.6 t0 5.0.0 for windows

### ISSUE THREAD

**Issue by myfear** [redhat-developer/docker-java#6]
Couldn't get any other combination to work on my machine.

VirtualBox-5.0.0-101573-Win.exe

Is the correct build.

**Comment by rafabene** [comment]
Interesting, because I had to update it because on Fedora, the docker-machine was hanging during the "create" with this version.

**Comment by myfear** [comment]
It's exactly the other way around for Windows.
They have some issues to sort out with that ;-)
